<?php

return [
    'AT' => 'Austria',
    'BE' => 'Belgium',
    'BG' => 'Bulgaria',
    'HR' => 'Croatia',
    'CZ' => 'Czech Republic',
    'DK' => 'Danmark',
    'UK' => 'England',
    'FR' => 'France',
    'DE' => 'Germany',
    'GR' => 'Greece',
    'HU' => 'Hungary',
    'IE' => 'Ireland',
    'IT' => 'Italy',
    'LV' => 'Lavia',
    'LU' => 'Luxembourg',
    'NL' => 'Netherlands',
    'PL' => 'Poland',
    'PT' => 'Portugal',
    'RO' => 'Romania',
    'SE' => 'Schweden',
    'SK' => 'Slowakia',
    'SI' => 'Slowenia',
    'SF' => 'Software Factory',
    'SA' => 'South Africa',
    'ES' => 'Spain',
    'CH' => 'Switzerland',
];
